{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMnrc0IQRUTjOUaEVIKQksX",
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/milca2310/app-controle-frota/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install streamlit\n"
      ],
      "metadata": {
        "collapsed": true,
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "jNbZaBE95rpx",
        "outputId": "9961744f-b09b-4d99-8ae3-e96284486a51"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting streamlit\n",
            "  Downloading streamlit-1.44.1-py3-none-any.whl.metadata (8.9 kB)\n",
            "Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (8.1.8)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging<25,>=20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (24.2)\n",
            "Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.2.2)\n",
            "Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (11.1.0)\n",
            "Requirement already satisfied: protobuf<6,>=3.20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.29.4)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.32.3)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (9.1.2)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (4.13.2)\n",
            "Collecting watchdog<7,>=2.1.5 (from streamlit)\n",
            "  Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m44.3/44.3 kB\u001b[0m \u001b[31m1.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.11/dist-packages (from streamlit) (3.1.44)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.11/dist-packages (from streamlit) (6.4.2)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (1.35.0)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.4.1)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2.3.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2025.1.31)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (25.3.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2024.10.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.2)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.24.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n",
            "Downloading streamlit-1.44.1-py3-none-any.whl (9.8 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m9.8/9.8 MB\u001b[0m \u001b[31m63.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.9/6.9 MB\u001b[0m \u001b[31m114.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl (79 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m79.1/79.1 kB\u001b[0m \u001b[31m9.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: watchdog, pydeck, streamlit\n",
            "Successfully installed pydeck-0.9.1 streamlit-1.44.1 watchdog-6.0.0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install pyngrok"
      ],
      "metadata": {
        "collapsed": true,
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "dGAZ1HSC5xC_",
        "outputId": "12c62047-8d85-46f2-937a-f5384925ab01"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: pyngrok in /usr/local/lib/python3.11/dist-packages (7.2.5)\n",
            "Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.11/dist-packages (from pyngrok) (6.0.2)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 13,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "V9QVoNR05RSt",
        "outputId": "e507af5f-4d26-442b-b710-a064e08c4154"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-04-25 17:50:11.619 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.619 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.621 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.622 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.623 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.623 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.624 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.625 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.627 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.628 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.628 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.630 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.631 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.632 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.633 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.634 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.635 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.636 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.638 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.638 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.640 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.640 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.641 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.641 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.644 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.644 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.645 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.645 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.646 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.647 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.647 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.648 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.648 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.649 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.649 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.650 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.650 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.651 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.652 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.652 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.653 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.653 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.654 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.654 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.655 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.656 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.656 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.657 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.657 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.658 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.659 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.660 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.660 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.661 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.661 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.662 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.663 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.663 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.664 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.664 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.665 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.665 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.677 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.680 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.681 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.681 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.682 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.682 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.683 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.683 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.684 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.685 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.685 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.686 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.686 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.693 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.693 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.695 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.695 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.698 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.698 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.701 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.701 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.702 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.703 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.703 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.705 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.705 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.707 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-25 17:50:11.708 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Banco de dados 'frota.db' excluído com sucesso.\n"
          ]
        }
      ],
      "source": [
        "import os\n",
        "import sqlite3\n",
        "import streamlit as st\n",
        "from datetime import date\n",
        "\n",
        "# Apagar o banco de dados existente (se for seguro fazer isso)\n",
        "if os.path.exists('frota.db'):\n",
        "    os.remove('frota.db')\n",
        "    print(\"Banco de dados 'frota.db' excluído com sucesso.\")\n",
        "else:\n",
        "    print(\"Banco de dados 'frota.db' não encontrado.\")\n",
        "\n",
        "# Conectando ao banco de dados SQLite\n",
        "conn = sqlite3.connect('frota.db', check_same_thread=True)\n",
        "c = conn.cursor()\n",
        "\n",
        "# Criando tabelas\n",
        "c.execute('''CREATE TABLE IF NOT EXISTS rota (\n",
        "    data TEXT,\n",
        "    km_inicio INTEGER,\n",
        "    km_fim INTEGER,\n",
        "    tipo_movel TEXT,\n",
        "    notas INTEGER,\n",
        "    valor_diario REAL,\n",
        "    problemas TEXT\n",
        ")''')\n",
        "\n",
        "c.execute('''CREATE TABLE IF NOT EXISTS abastecimento (\n",
        "    data TEXT,\n",
        "    litros REAL,\n",
        "    valor_abastecimento REAL,\n",
        "    km_atual INTEGER,\n",
        "    tipo_carga TEXT\n",
        ")''')\n",
        "\n",
        "c.execute('''CREATE TABLE IF NOT EXISTS manutencao (\n",
        "    tipo_manutencao TEXT,\n",
        "    data_manutencao TEXT,\n",
        "    quilometragem INTEGER,\n",
        "    proxima_manutencao INTEGER\n",
        ")''')\n",
        "\n",
        "# Layout do Streamlit\n",
        "st.markdown(\"\"\"\n",
        "    <h1 style='text-align: center; color: #795548;'>📋 Controle Diário da Frota</h1>\n",
        "    <h4 style='text-align: center; color: #A1887F;'>Registre tudo do seu dia em um só lugar</h4>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "\n",
        "abas = st.tabs([\"🚚 Rota do Dia\", \"🛢 Abastecimento\", \"🔧 Manutenção\", \"📦 Entregas\", \"📊 Relatórios\"])\n",
        "\n",
        "# Função para calcular o custo por KM\n",
        "def calcular_custo_por_km():\n",
        "    try:\n",
        "        c.execute('''SELECT SUM(abastecimento.valor_abastecimento), SUM(rota.km_fim - rota.km_inicio)\n",
        "                     FROM abastecimento\n",
        "                     JOIN rota ON abastecimento.km_atual = rota.km_fim''')\n",
        "        resultado = c.fetchone()\n",
        "\n",
        "        if resultado[0] is not None and resultado[1] is not None:\n",
        "            valor_abastecimento_total, km_total = resultado\n",
        "            if km_total > 0:\n",
        "                custo_km = valor_abastecimento_total / km_total\n",
        "                st.write(f\"Custo por KM: R$ {custo_km:.2f}\")\n",
        "                if custo_km > 2:  # Alerta se o custo por KM for maior que R$2\n",
        "                    st.warning(\"⚠ O custo por KM está muito alto! Verifique seus gastos.\")\n",
        "            else:\n",
        "                st.warning(\"⚠ Não há dados suficientes para calcular o custo por KM.\")\n",
        "        else:\n",
        "            st.warning(\"⚠ Não há dados suficientes de abastecimento ou rota para calcular o custo por KM.\")\n",
        "    except Exception as e:\n",
        "        st.error(f\"Ocorreu um erro ao calcular o custo por KM: {e}\")\n",
        "\n",
        "# Função para verificar manutenções\n",
        "def verificar_manutencao():\n",
        "    try:\n",
        "        c.execute(\"SELECT tipo_manutencao, quilometragem, proxima_manutencao FROM manutencao\")\n",
        "        manutencao = c.fetchall()\n",
        "        if not manutencao:\n",
        "            st.warning(\"⚠ Não há registros de manutenção.\")\n",
        "        for m in manutencao:\n",
        "            tipo, km_atual, proxima_manutencao = m\n",
        "            try:\n",
        "                km_atual = int(km_atual)\n",
        "                proxima_manutencao = int(proxima_manutencao)\n",
        "            except ValueError:\n",
        "                continue\n",
        "            if km_atual >= proxima_manutencao:\n",
        "                st.warning(f\"⚠ A manutenção de {tipo} está atrasada! Quilometragem atual: {km_atual}. Próxima manutenção em: {proxima_manutencao}.\")\n",
        "    except Exception as e:\n",
        "        st.error(f\"Ocorreu um erro ao verificar as manutenções: {e}\")\n",
        "\n",
        "# Aba Rota do Dia\n",
        "with abas[0]:\n",
        "    st.subheader(\"Rota do Dia\")\n",
        "    data = st.date_input(\"Data\", value=date.today(), key=\"rota_data\")\n",
        "    km_inicio = st.number_input(\"KM Inicial\", min_value=0)\n",
        "    km_fim = st.number_input(\"KM Final\", min_value=0)\n",
        "    tipo_movel = st.text_input(\"Tipo de Móvel Transportado\")\n",
        "    notas = st.number_input(\"Número de Notas no Dia\", min_value=0)\n",
        "    valor_diario = st.number_input(\"Valor Diário Recebido (R$)\", min_value=0.0)\n",
        "    problemas = st.text_area(\"Problemas do Dia (devoluções, quebras...)\")\n",
        "\n",
        "    if st.button(\"Salvar Rota\"):\n",
        "        try:\n",
        "            c.execute('''INSERT INTO rota VALUES (?, ?, ?, ?, ?, ?, ?)''',\n",
        "                      (str(data), km_inicio, km_fim, tipo_movel, notas, valor_diario, problemas))\n",
        "            conn.commit()\n",
        "            st.success(\"Rota registrada com sucesso!\")\n",
        "        except Exception as e:\n",
        "            st.error(f\"Ocorreu um erro ao salvar a rota: {e}\")\n",
        "\n",
        "# Aba Abastecimento\n",
        "with abas[1]:\n",
        "    st.subheader(\"Registro de Abastecimento\")\n",
        "    data_ab = st.date_input(\"Data do Abastecimento\", value=date.today(), key=\"abastecimento_data\")\n",
        "    litros = st.number_input(\"Litros Abastecidos\", min_value=0.0, key=\"litros\")\n",
        "    valor_abastecimento = st.number_input(\"Valor Pago (R$)\", min_value=0.0, key=\"valor_abastecimento\")\n",
        "    km_atual = st.number_input(\"Quilometragem Atual\", min_value=0, key=\"km_atual\")\n",
        "    tipo_carga = st.text_input(\"Tipo de Carga (opcional)\", key=\"tipo_carga\")\n",
        "\n",
        "    if st.button(\"Salvar Abastecimento\"):\n",
        "        try:\n",
        "            c.execute('''INSERT INTO abastecimento VALUES (?, ?, ?, ?, ?)''',\n",
        "                      (str(data_ab), litros, valor_abastecimento, km_atual, tipo_carga))\n",
        "            conn.commit()\n",
        "            st.success(\"Abastecimento registrado com sucesso!\")\n",
        "        except Exception as e:\n",
        "            st.error(f\"Ocorreu um erro ao salvar o abastecimento: {e}\")\n",
        "\n",
        "# Aba Manutenção\n",
        "with abas[2]:\n",
        "    st.subheader(\"Registro de Manutenção\")\n",
        "    tipo_manutencao = st.text_input(\"Tipo de Manutenção\")\n",
        "    data_manutencao = st.date_input(\"Data da Manutenção\", value=date.today(), key=\"manutencao_data\")\n",
        "    quilometragem = st.number_input(\"Quilometragem\", min_value=0)\n",
        "    proxima_manutencao = st.number_input(\"Próxima Manutenção (KM)\", min_value=0)\n",
        "\n",
        "    if st.button(\"Salvar Manutenção\"):\n",
        "        try:\n",
        "            c.execute('''INSERT INTO manutencao VALUES (?, ?, ?, ?)''',\n",
        "                      (tipo_manutencao, str(data_manutencao), quilometragem, proxima_manutencao))\n",
        "            conn.commit()\n",
        "            st.success(\"Manutenção registrada com sucesso!\")\n",
        "        except Exception as e:\n",
        "            st.error(f\"Ocorreu um erro ao salvar a manutenção: {e}\")\n",
        "\n",
        "# Alertas\n",
        "verificar_manutencao()\n",
        "calcular_custo_por_km()\n",
        "\n",
        "# Fechar a conexão ao banco de dados após o uso\n",
        "conn.close()\n",
        "\n"
      ]
    }
  ]
}
